### ISSUE TITLE
Please open account

### ISSUE THREAD

**Issue by natehouk** [hey-api/upload-openapi-spec#10]
Hey api,

Please open an account for me, my email is nate@epsilonrecords.com

Thank you,
Nate

**Comment by mrlubos** [comment]
Hey @natehouk, I've sent you an email 8 days ago but haven't heard back. Please respond if you'd like to continue the conversation, I am going to close this issue.

**Comment by natehouk** [comment]
Thanks, I have reverted.

**Comment by mrlubos** [comment]
Hey, check out the updated README! https://github.com/hey-api/upload-openapi-spec

And of course happy to talk/do a demo https://calendly.com/lubos-heyapi/new-meeting
