### ISSUE TITLE
Please open an account

### ISSUE THREAD

**Issue by vkuprin** [hey-api/upload-openapi-spec#11]
Hey api,

Please open an account for me, my email is [vitas_s@inbox.lv](mailto:vitas_s@inbox.lv)

Thank you,
Vitaly

**Comment by mrlubos** [comment]
Hey, check out the updated README! https://github.com/hey-api/upload-openapi-spec

And of course happy to talk/do a demo https://calendly.com/lubos-heyapi/new-meeting
